In [3]:
#Loading all necessary libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from keras.utils import to_categorical
import keras as kr
kr.__version__

'2.1.3'

In [62]:
#Loading and viewing iris dataset
dataset = pd.read_csv("https://raw.githubusercontent.com/uiuc-cse/data-fa14/gh-pages/data/iris.csv")
dataset

URLError: <urlopen error [Errno 11001] getaddrinfo failed>

In [37]:
X = dataset.values[:, 0:4]
y = dataset.values[:, 4]
X.shape
y.shape

(150,)

In [38]:
from sklearn.preprocessing import LabelEncoder
encoder =  LabelEncoder()
y1 = encoder.fit_transform(y)

Y = pd.get_dummies(y1).values


from sklearn.model_selection import train_test_split
X_train,X_test, y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state=0) 

In [39]:
#Defining the model 

from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD,Adam

In [47]:
#Input and Output layers directly connected network
model = Sequential()

model.add(Dense(units=3, activation='softmax', input_dim=4))
model.compile(loss="categorical_crossentropy", optimizer="adam", metrics = ['accuracy'])
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_7 (Dense)              (None, 3)                 15        
Total params: 15
Trainable params: 15
Non-trainable params: 0
_________________________________________________________________


In [49]:
#Calculating accuracy for Input and Output layer directly connected network

model.fit(X_train,y_train,epochs=100)
y_pred = model.predict(X_test)

y_test_class = np.argmax(y_test,axis=1)
y_pred_class = np.argmax(y_pred,axis=1)

Epoch 1/100
120/120 [==============================] - 0s 105us/step - loss: 0.6932 - acc: 0.7000
Epoch 2/100
120/120 [==============================] - 0s 79us/step - loss: 0.6915 - acc: 0.7000
Epoch 3/100
120/120 [==============================] - 0s 68us/step - loss: 0.6895 - acc: 0.7000
Epoch 4/100
120/120 [==============================] - 0s 76us/step - loss: 0.6875 - acc: 0.6917
Epoch 5/100
120/120 [==============================] - 0s 85us/step - loss: 0.6857 - acc: 0.6917
Epoch 6/100
120/120 [==============================] - 0s 96us/step - loss: 0.6838 - acc: 0.6917
Epoch 7/100
120/120 [==============================] - 0s 70us/step - loss: 0.6820 - acc: 0.7000
Epoch 8/100
120/120 [==============================] - 0s 105us/step - loss: 0.6801 - acc: 0.7000
Epoch 9/100
120/120 [==============================] - 0s 94us/step - loss: 0.6784 - acc: 0.7000
Epoch 10/100
120/120 [==============================] - 0s 104us/step - loss: 0.6766 - acc: 0.7000
Epoch 11/100
120/120 [====

In [52]:
#Accuracy of the predicted values of model without hidden layers

from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test_class,y_pred_class))
print(confusion_matrix(y_test_class,y_pred_class))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        11
          1       0.75      0.23      0.35        13
          2       0.33      0.83      0.48         6

avg / total       0.76      0.63      0.61        30

[[11  0  0]
 [ 0  3 10]
 [ 0  1  5]]


In [55]:
#Adding Single hidden layer with 10 neurons
model1 = Sequential()

model1.add(Dense(10,input_shape=(4,),activation='relu'))
model1.add(Dense(3,activation='softmax'))
model1.compile(Adam(lr=0.04),'categorical_crossentropy',metrics=['accuracy'])

model1.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_10 (Dense)             (None, 10)                50        
_________________________________________________________________
dense_11 (Dense)             (None, 3)                 33        
Total params: 83
Trainable params: 83
Non-trainable params: 0
_________________________________________________________________


In [56]:
#Calculating accuracy for Single hidden layer NN

model1.fit(X_train,y_train,epochs=100)
y_pred = model1.predict(X_test)

y_test_class = np.argmax(y_test,axis=1)
y_pred_class = np.argmax(y_pred,axis=1)

Epoch 1/100
120/120 [==============================] - 1s 6ms/step - loss: 1.7807 - acc: 0.2083
Epoch 2/100
120/120 [==============================] - 0s 171us/step - loss: 1.1697 - acc: 0.2417
Epoch 3/100
120/120 [==============================] - 0s 175us/step - loss: 0.8824 - acc: 0.5583
Epoch 4/100
120/120 [==============================] - 0s 78us/step - loss: 0.7254 - acc: 0.5833
Epoch 5/100
120/120 [==============================] - 0s 108us/step - loss: 0.6148 - acc: 0.6167
Epoch 6/100
120/120 [==============================] - 0s 117us/step - loss: 0.5337 - acc: 0.6917
Epoch 7/100
120/120 [==============================] - 0s 54us/step - loss: 0.4860 - acc: 0.8417
Epoch 8/100
120/120 [==============================] - 0s 113us/step - loss: 0.4277 - acc: 0.8083
Epoch 9/100
120/120 [==============================] - 0s 151us/step - loss: 0.3825 - acc: 0.8500
Epoch 10/100
120/120 [==============================] - 0s 118us/step - loss: 0.3533 - acc: 0.9167
Epoch 11/100
120/120 [=

In [57]:
#Accuracy of the predicted values from Model1 with one hidden layer

from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test_class,y_pred_class))
print(confusion_matrix(y_test_class,y_pred_class))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        11
          1       1.00      1.00      1.00        13
          2       1.00      1.00      1.00         6

avg / total       1.00      1.00      1.00        30

[[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]


In [58]:
#Adding Three hidden layers to network
model2 = Sequential()

model2.add(Dense(10,input_shape=(4,),activation='tanh'))
model2.add(Dense(8,activation='tanh'))
model2.add(Dense(6,activation='tanh'))
model2.add(Dense(3,activation='softmax'))

model2.compile(loss="categorical_crossentropy", optimizer="adam", metrics = ['accuracy'])

model2.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_12 (Dense)             (None, 10)                50        
_________________________________________________________________
dense_13 (Dense)             (None, 8)                 88        
_________________________________________________________________
dense_14 (Dense)             (None, 6)                 54        
_________________________________________________________________
dense_15 (Dense)             (None, 3)                 21        
Total params: 213
Trainable params: 213
Non-trainable params: 0
_________________________________________________________________


In [59]:
#Calculating accuracy for Three hidden layers NN

model1.fit(X_train,y_train,epochs=100)
y_pred = model1.predict(X_test)

y_test_class = np.argmax(y_test,axis=1)
y_pred_class = np.argmax(y_pred,axis=1)

Epoch 1/100
120/120 [==============================] - 0s 2ms/step - loss: 0.0728 - acc: 0.9667
Epoch 2/100
120/120 [==============================] - 0s 72us/step - loss: 0.0652 - acc: 0.9750
Epoch 3/100
120/120 [==============================] - 0s 108us/step - loss: 0.0628 - acc: 0.9833
Epoch 4/100
120/120 [==============================] - 0s 106us/step - loss: 0.0599 - acc: 0.9833
Epoch 5/100
120/120 [==============================] - 0s 115us/step - loss: 0.0598 - acc: 0.9833
Epoch 6/100
120/120 [==============================] - 0s 92us/step - loss: 0.0750 - acc: 0.9667
Epoch 7/100
120/120 [==============================] - 0s 92us/step - loss: 0.0908 - acc: 0.9583
Epoch 8/100
120/120 [==============================] - 0s 94us/step - loss: 0.0964 - acc: 0.9583
Epoch 9/100
120/120 [==============================] - 0s 89us/step - loss: 0.1314 - acc: 0.9667
Epoch 10/100
120/120 [==============================] - 0s 134us/step - loss: 0.0673 - acc: 0.9667
Epoch 11/100
120/120 [====

In [60]:
#Accuracy of the predicted values from Model2 with three hidden layers

from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test_class,y_pred_class))
print(confusion_matrix(y_test_class,y_pred_class))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        11
          1       1.00      1.00      1.00        13
          2       1.00      1.00      1.00         6

avg / total       1.00      1.00      1.00        30

[[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]
